'use strict'

module.exports = {
  TIME_TO_FINISH_THE_CONTEST: 21,
  TIMES_TO_START_THE_CONTEST: [9, 10, 20, 21],
  HOURS_TO_ADD_WHEN_CONTEST_DRAW: 1,
  WEEK_PERIOD: 7,
  FIRST_PAGE: 1,
  NUMBER_OF_FANS_IN_PAGE: 30,
  NUMBER_OF_CONTESTS_IN_PAGE: 5,
  NUMBER_OF_CONTESTANTS_IN_PAGE: 40,
  NUMBER_OF_COVERS_IN_PAGE: 20,
  NUMBER_OF_COVERS_IN_SUMMARIZED_LIST: 8,
  NUMBER_OF_ARTISTS_IN_INDEX_VIEW: 6,
  NUMBER_OF_ARTISTS_IN_SUMMARIZED_LIST: 8,
  NUMBER_OF_MUSICS_BY_ARTIST: 5,
  NUMBER_OF_COVERS_OF_MUSIC: 12,
  NUMBER_OF_ARTISTS_IN_PAGE: 60,
  NUMBER_OF_AUDITIONS_IN_PAGE: 60,
  POWER_VOTING_INCREMENT_FOR_THE_GOLD_MEDAL_VOTER: 0.1,
  POWER_VOTING_INCREMENT_FOR_THE_SILVER_MEDAL_VOTER: 0.05,
  POWER_VOTING_INCREMENT_FOR_THE_BRONZE_MEDAL_VOTER: 0.025,
  VOTE_LIMIT: 5,
  incentiveVote: {
    firstEmail: {
      DAYS_BEFORE_THE_END: 7,
    },
    secondEmail: {
      DAYS_BEFORE_THE_END: 3,
    },
    HOUR_TO_SEND_EMAIL: 14,
    MINUTE_TO_SEND_EMAIL: 0,
    SECOND_TO_SEND_EMAIL: 0
  }
}