module.exports = {
  WEEK_PERIOD: 7,
  FIRST_PAGE: 1,
  NUMBER_OF_COVERS_IN_LIST: 20,
  NUMBER_OF_COVERS_IN_SUMMARIZED_LIST: 8,
  NUMBER_OF_ARTISTS_IN_SUMMARIZED_LIST: 8,
  NUMBER_OF_MUSICS_BY_ARTIST: 5,
  NUMBER_OF_COVERS_OF_MUSIC: 12,
  ARTISTS_IN_LIST: 60,
  NUMBER_OF_AUDITIONS_IN_LIST: 40
}