module.exports = {
  WEEK_PERIOD: 7,
  FIRST_PAGE: 1,
  NUMBER_OF_COVERS_IN_LIST: 20,
  NUMBER_OF_COVERS_IN_SUMMARIZED_LIST: 8,
  NUMBER_OF_ARTISTS_IN_INDEX_VIEW: 6,
  NUMBER_OF_ARTISTS_IN_SUMMARIZED_LIST: 8,
  NUMBER_OF_MUSICS_BY_ARTIST: 5,
  NUMBER_OF_COVERS_OF_MUSIC: 12,
  ARTISTS_IN_LIST: 60,
  NUMBER_OF_AUDITIONS_IN_LIST: 35,
  VOTE_LIMIT: 5,
  POWER_VOTING_INCREMENT_FOR_THE_GOLD_MEDAL_VOTER: 0.1,
  POWER_VOTING_INCREMENT_FOR_THE_SILVER_MEDAL_VOTER: 0.05,
  POWER_VOTING_INCREMENT_FOR_THE_BRONZE_MEDAL_VOTER: 0.025
}